// <auto-generated />
using DataAccessLayer.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20211216095025_mig1")]
    partial class mig1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("EntityLayer.Concrete.Arac", b =>
                {
                    b.Property<int>("AracID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("AracBg")
                        .HasColumnType("int");

                    b.Property<string>("Donanim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fiyat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Marka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Marka_id")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Model_id")
                        .HasColumnType("int");

                    b.Property<string>("Motor_hacmi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vites_tipi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yakit_tipi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AracID");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Gallery", b =>
                {
                    b.Property<int>("GalleryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("GalleryAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GalleryResim")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GalleryID");

                    b.ToTable("Gallerys");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Kullanici", b =>
                {
                    b.Property<int>("KullaniciID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Kullanici_AdSoyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kullanici_Tarih")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Marka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Plaka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KullaniciID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Opsiyonlar", b =>
                {
                    b.Property<int>("Opsiyon_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Marka_id")
                        .HasColumnType("int");

                    b.Property<int>("Model_id")
                        .HasColumnType("int");

                    b.Property<string>("Opsiyon_Adi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opsiyon_Fiyati")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Opsiyon_ID");

                    b.ToTable("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
